name: analysis_options
version: 1.0.0
description: Strict Analysis Options
homepage: https://github.com/vaetas/analysis_options

environment:
  sdk: '>=2.8.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
